#!/usr/bin/env node
// design-sync PREPARE — deterministic pre-converter setup for @repo/ui.
//
// Run this ONCE before every converter/driver run:
//   node .design-sync/prepare.mjs
// It is idempotent, recorded as cfg.buildCmd, and is THE thing that makes a
// re-sync reproducible. Without it the converter falls back to stale/empty
// artifacts.
//
// Why it's needed (see .design-sync/NOTES.md for the full story):
//   @repo/ui has NO JS build (ships raw .tsx) and uses Tailwind v4 (no compiled
//   CSS ships). The converter needs three things this script regenerates from
//   source, none of which are committed (they're derived):
//     1. a self-symlink node_modules/@repo/ui -> packages/ui, so PKG_DIR
//        resolves and the self-referential @repo/ui/* imports resolve via the
//        package exports map;
//     2. a fresh .d.ts tree (packages/ui/dist) via the repo's own tsc — the
//        source of truth for prop extraction (a stale dist tree silently
//        poisons it with wrong props, so we wipe dist first);
//     3. compiled Tailwind CSS (dist/ds-compiled.css) + the Inter @font-face
//        CSS (dist/inter-latin.css), which cfg.cssEntry / cfg.extraFonts point at.
//
// Prereq: .ds-sync/ is already staged with its deps (the skill's `cp -r` +
// `npm i` step). This script installs @tailwindcss/cli into .ds-sync on demand
// if it's missing, so it self-heals on a fresh clone.

import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url)); // .design-sync
const ROOT = resolve(HERE, ".."); // repo root
const UI = join(ROOT, "packages/ui");
const DIST = join(UI, "dist");
const NM = join(UI, "node_modules");
const DS = join(ROOT, ".ds-sync");
const log = (m) => console.error(`[prepare] ${m}`);
const kb = (p) => Math.round(statSync(p).size / 1024);

// Authored @font-face rules for the families the tokens actually NAME:
// --font-sans is "Inter Variable" and --font-mono / --font-geist* are the
// Geist pair (globals.css). The old self-hosted InterVariable.ttf is gone
// from the tree, so the faces come from the fontsource-variable packages in
// the workspace store — latin wght subsets copied into dist/fonts/ below.
// cfg.extraFonts points at dist/inter-latin.css; the converter copies the
// woff2 url() targets into the bundle's fonts/ and rewrites the urls.
const INTER_LATIN_CSS = `/* Token-named faces (Inter Variable + Geist pair), fontsource latin subsets.
   Generated by .design-sync/prepare.mjs. */
@font-face {
  font-family: "Inter Variable";
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(fonts/inter-latin-wght-normal.woff2) format("woff2-variations");
}
@font-face {
  font-family: "Geist Variable";
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(fonts/geist-latin-wght-normal.woff2) format("woff2-variations");
}
@font-face {
  font-family: "Geist Mono Variable";
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(fonts/geist-mono-latin-wght-normal.woff2) format("woff2-variations");
}
`;

// The three woff2 subsets, resolved from whichever workspace package carries
// the fontsource dep (geist pair are @repo/ui deps; inter rides apps/web).
const FONT_FILES = [
  [
    "@fontsource-variable/inter/files/inter-latin-wght-normal.woff2",
    "inter-latin-wght-normal.woff2",
  ],
  [
    "@fontsource-variable/geist/files/geist-latin-wght-normal.woff2",
    "geist-latin-wght-normal.woff2",
  ],
  [
    "@fontsource-variable/geist-mono/files/geist-mono-latin-wght-normal.woff2",
    "geist-mono-latin-wght-normal.woff2",
  ],
];

function fail(m) {
  console.error(`[prepare] ERROR: ${m}`);
  process.exit(1);
}

if (!existsSync(UI)) fail(`packages/ui not found at ${UI}`);
if (!existsSync(join(NM, "react"))) {
  fail("packages/ui/node_modules/react missing — run the repo install (pnpm i) first");
}

// ── 1. self-symlink ────────────────────────────────────────────────────────
const linkDir = join(NM, "@repo");
const link = join(linkDir, "ui");
mkdirSync(linkDir, { recursive: true });
try {
  rmSync(link, { recursive: true, force: true });
} catch {}
symlinkSync(UI, link); // absolute target — survives cwd changes
log(`self-symlink @repo/ui -> packages/ui`);

// ── 2. fresh .d.ts (wipe dist first to kill any stale tree) ─────────────────
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
// tsconfig.base has incremental:true → a stale tsBuildInfoFile makes tsc skip
// emit after we wipe dist. Clear it so the emit is always full. (--incremental
// false is also passed below as belt-and-suspenders.)
rmSync(join(UI, ".cache/tsbuildinfo.json"), { force: true });
const tsc = join(NM, ".bin/tsc");
if (!existsSync(tsc)) fail("packages/ui/node_modules/.bin/tsc missing — run pnpm i");
try {
  execFileSync(
    tsc,
    [
      "-p",
      "tsconfig.json",
      "--declaration",
      "--emitDeclarationOnly",
      "--noEmit",
      "false",
      "--incremental",
      "false",
      "--rootDir",
      "src",
      "--outDir",
      "dist",
      "--skipLibCheck",
    ],
    { cwd: UI, stdio: "ignore" },
  );
} catch {
  // tsc exits non-zero on type errors but still emits .d.ts — expected. Verify below.
}
const countDts = (dir) =>
  readdirSync(dir, { withFileTypes: true }).reduce((n, e) => {
    const p = join(dir, e.name);
    return n + (e.isDirectory() ? countDts(p) : e.name.endsWith(".d.ts") ? 1 : 0);
  }, 0);
const dts = countDts(DIST);
if (dts === 0) fail("tsc emitted no .d.ts — check packages/ui/tsconfig.json");
log(`fresh .d.ts: ${dts} files`);

// ── 3. compiled Tailwind CSS + Inter font CSS ───────────────────────────────
let twcli = join(DS, "node_modules/.bin/tailwindcss");
if (!existsSync(twcli)) {
  if (!existsSync(DS)) fail(`.ds-sync not staged — copy the skill scripts + npm i first`);
  log("installing @tailwindcss/cli into .ds-sync ...");
  execFileSync("npm", ["i", "@tailwindcss/cli@^4", "--cache", join(DS, ".npm-cache")], {
    cwd: DS,
    stdio: "inherit",
  });
}
const cssOut = join(DIST, "ds-compiled.css");
execFileSync(twcli, ["-i", join(HERE, "tailwind-entry.css"), "-o", cssOut], { stdio: "inherit" });
// Strip inlined @font-face (fontsource @import inlines them with unresolvable
// ./files/ urls; real fonts are wired via cfg.extraFonts → inter-latin.css).
let css = readFileSync(cssOut, "utf8");
const before = (css.match(/@font-face/g) || []).length;
css = css.replace(/@font-face\s*\{[^}]*\}/g, "");
writeFileSync(cssOut, css);
log(`compiled CSS: dist/ds-compiled.css (${kb(cssOut)} KB, stripped ${before} @font-face)`);

{
  const fontsDir = join(DIST, "fonts");
  mkdirSync(fontsDir, { recursive: true });
  for (const [spec, outName] of FONT_FILES) {
    let resolved = null;
    for (const base of [
      join(UI, "node_modules"),
      join(ROOT, "apps/web/node_modules"),
      join(ROOT, "node_modules"),
    ]) {
      const candidate = join(base, spec);
      if (existsSync(candidate)) {
        resolved = candidate;
        break;
      }
    }
    if (resolved === null) {
      // Not linked into any workspace package — fall back to the pnpm store
      // (inter is an orphan there; the token still names its family).
      const pkgName = spec.split("/files/")[0];
      const storeKey = pkgName.replace("/", "+") + "@";
      const store = join(ROOT, "node_modules", ".pnpm");
      if (existsSync(store)) {
        for (const entry of readdirSync(store)) {
          if (!entry.startsWith(storeKey)) continue;
          const candidate = join(store, entry, "node_modules", spec);
          if (existsSync(candidate)) {
            resolved = candidate;
            break;
          }
        }
      }
    }
    if (resolved === null)
      fail(`font source missing: ${spec} — is the fontsource package installed?`);
    copyFileSync(resolved, join(fontsDir, outName));
  }
}
writeFileSync(join(DIST, "inter-latin.css"), INTER_LATIN_CSS);
log(`wrote dist/inter-latin.css (Inter Latin @font-face)`);

log("done — ready for package-build.mjs / resync.mjs");
