#!/usr/bin/env node
// design-sync PREPARE — deterministic pre-converter setup for @repo/ui.
//
// Run this ONCE before every converter/driver run:
//   node .design-sync/prepare.mjs
// It is idempotent, recorded as cfg.buildCmd, and is THE thing that makes a
// re-sync reproducible. Without it the converter falls back to stale/empty
// artifacts.
//
// Why it's needed (see .design-sync/NOTES.md for the full story):
//   @repo/ui has NO JS build (ships raw .tsx) and uses Tailwind v4 (no compiled
//   CSS ships). The converter needs three things this script regenerates from
//   source, none of which are committed (they're derived):
//     1. a self-symlink node_modules/@repo/ui -> packages/ui, so PKG_DIR
//        resolves and the self-referential @repo/ui/* imports resolve via the
//        package exports map;
//     2. a fresh .d.ts tree (packages/ui/dist) via the repo's own tsc — the
//        source of truth for prop extraction (a stale dist tree silently
//        poisons it with wrong props, so we wipe dist first);
//     3. compiled Tailwind CSS (dist/ds-compiled.css) + the Inter @font-face
//        CSS (dist/inter-latin.css), which cfg.cssEntry / cfg.extraFonts point at.
//
// Prereq: .ds-sync/ is already staged with its deps (the skill's `cp -r` +
// `npm i` step). This script installs @tailwindcss/cli into .ds-sync on demand
// if it's missing, so it self-heals on a fresh clone.

import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url)); // .design-sync
const ROOT = resolve(HERE, ".."); // repo root
const UI = join(ROOT, "packages/ui");
const DIST = join(UI, "dist");
const NM = join(UI, "node_modules");
const DS = join(ROOT, ".ds-sync");
const log = (m) => console.error(`[prepare] ${m}`);
const kb = (p) => Math.round(statSync(p).size / 1024);

// Authored Inter @font-face (Latin subsets only — the DS bundle doesn't need
// fontsource's 42 subsets). Written into dist so nothing authored lives in a
// committed-but-derived location; cfg.extraFonts points at dist/inter-latin.css.
// url() is resolved by the converter relative to this file's dir (dist/).
const INTER_LATIN_CSS = `/* Inter Variable — Latin subsets only (variable weight), self-hosted.
   Generated by .design-sync/prepare.mjs. design-sync copies the referenced
   woff2 into the bundle's fonts/ and rewrites these urls. */
@font-face {
  font-family: "Inter Variable";
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(../node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2) format("woff2-variations");
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: "Inter Variable";
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(../node_modules/@fontsource-variable/inter/files/inter-latin-ext-wght-normal.woff2) format("woff2-variations");
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
`;

function fail(m) {
  console.error(`[prepare] ERROR: ${m}`);
  process.exit(1);
}

if (!existsSync(UI)) fail(`packages/ui not found at ${UI}`);
if (!existsSync(join(NM, "react"))) {
  fail("packages/ui/node_modules/react missing — run the repo install (pnpm i) first");
}

// ── 1. self-symlink ────────────────────────────────────────────────────────
const linkDir = join(NM, "@repo");
const link = join(linkDir, "ui");
mkdirSync(linkDir, { recursive: true });
try {
  rmSync(link, { recursive: true, force: true });
} catch {}
symlinkSync(UI, link); // absolute target — survives cwd changes
log(`self-symlink @repo/ui -> packages/ui`);

// 1b. fork node_modules symlink — .design-sync/overrides/source-kit.mjs imports
// bare `ts-morph`; node resolves it from .design-sync/node_modules. Gitignored,
// so recreate each clone.
const forkNm = join(HERE, "node_modules");
if (existsSync(join(DS, "node_modules"))) {
  try {
    rmSync(forkNm, { recursive: true, force: true });
  } catch {}
  symlinkSync(join(DS, "node_modules"), forkNm);
  log(`fork node_modules -> .ds-sync/node_modules`);
}

// ── 2. fresh .d.ts (wipe dist first to kill any stale tree) ─────────────────
rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
// tsconfig.base has incremental:true → a stale tsBuildInfoFile makes tsc skip
// emit after we wipe dist. Clear it so the emit is always full. (--incremental
// false is also passed below as belt-and-suspenders.)
rmSync(join(UI, ".cache/tsbuildinfo.json"), { force: true });
const tsc = join(NM, ".bin/tsc");
if (!existsSync(tsc)) fail("packages/ui/node_modules/.bin/tsc missing — run pnpm i");
try {
  execFileSync(
    tsc,
    [
      "-p",
      "tsconfig.json",
      "--declaration",
      "--emitDeclarationOnly",
      "--noEmit",
      "false",
      "--incremental",
      "false",
      "--rootDir",
      "src",
      "--outDir",
      "dist",
      "--skipLibCheck",
    ],
    { cwd: UI, stdio: "ignore" },
  );
} catch {
  // tsc exits non-zero on type errors but still emits .d.ts — expected. Verify below.
}
const countDts = (dir) =>
  readdirSync(dir, { withFileTypes: true }).reduce((n, e) => {
    const p = join(dir, e.name);
    return n + (e.isDirectory() ? countDts(p) : e.name.endsWith(".d.ts") ? 1 : 0);
  }, 0);
const dts = countDts(DIST);
if (dts === 0) fail("tsc emitted no .d.ts — check packages/ui/tsconfig.json");
log(`fresh .d.ts: ${dts} files`);

// ── 3. compiled Tailwind CSS + Inter font CSS ───────────────────────────────
let twcli = join(DS, "node_modules/.bin/tailwindcss");
if (!existsSync(twcli)) {
  if (!existsSync(DS)) fail(`.ds-sync not staged — copy the skill scripts + npm i first`);
  log("installing @tailwindcss/cli into .ds-sync ...");
  execFileSync("npm", ["i", "@tailwindcss/cli@^4", "--cache", join(DS, ".npm-cache")], {
    cwd: DS,
    stdio: "inherit",
  });
}
const cssOut = join(DIST, "ds-compiled.css");
execFileSync(twcli, ["-i", join(HERE, "tailwind-entry.css"), "-o", cssOut], { stdio: "inherit" });
// Strip inlined @font-face (fontsource @import inlines them with unresolvable
// ./files/ urls; real fonts are wired via cfg.extraFonts → inter-latin.css).
let css = readFileSync(cssOut, "utf8");
const before = (css.match(/@font-face/g) || []).length;
css = css.replace(/@font-face\s*\{[^}]*\}/g, "");
writeFileSync(cssOut, css);
log(`compiled CSS: dist/ds-compiled.css (${kb(cssOut)} KB, stripped ${before} @font-face)`);

writeFileSync(join(DIST, "inter-latin.css"), INTER_LATIN_CSS);
log(`wrote dist/inter-latin.css (Inter Latin @font-face)`);

log("done — ready for package-build.mjs / resync.mjs");
