/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppForgotPasswordRouteImport } from './routes/app/forgot-password'
import { Route as AppSignInRouteImport } from './routes/app/sign-in'
import { Route as AppSignUpRouteImport } from './routes/app/sign-up'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInRoute = AppSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppRoute,
} as any)
const AppSignUpRoute = AppSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/sign-in': typeof AppSignInRoute
  '/app/sign-up': typeof AppSignUpRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/sign-in': typeof AppSignInRoute
  '/app/sign-up': typeof AppSignUpRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/sign-in': typeof AppSignInRoute
  '/app/sign-up': typeof AppSignUpRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/robots.txt'
    | '/app/forgot-password'
    | '/app/sign-in'
    | '/app/sign-up'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/app/forgot-password'
    | '/app/sign-in'
    | '/app/sign-up'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/robots.txt'
    | '/app/forgot-password'
    | '/app/sign-in'
    | '/app/sign-up'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forgot-password': {
      id: '/app/forgot-password'
      path: '/forgot-password'
      fullPath: '/app/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sign-in': {
      id: '/app/sign-in'
      path: '/sign-in'
      fullPath: '/app/sign-in'
      preLoaderRoute: typeof AppSignInRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sign-up': {
      id: '/app/sign-up'
      path: '/sign-up'
      fullPath: '/app/sign-up'
      preLoaderRoute: typeof AppSignUpRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppSignInRoute: typeof AppSignInRoute
  AppSignUpRoute: typeof AppSignUpRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppSignInRoute: AppSignInRoute,
  AppSignUpRoute: AppSignUpRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
