// Inline AI for the editor — continue / summarize / improve / shorten / fix,
// generated by the isolated no-tools agent (main/inline-ai.ts) and inserted as a
// highlighted "pending" range the user can Accept (keep) or Discard (remove).
//
// The pending text carries a transient `ai` leaf mark (for the highlight) and is
// tracked by a rangeRef so accept/discard target it exactly even if the doc
// shifts. The mark has no markdown form, so it's simply dropped on serialize —
// accepting just removes the highlight; the text was already in the document.

import { useCallback, useRef, useState } from "react";
import { type TRange, RangeApi } from "platejs";
import { createPlatePlugin, type PlateEditor } from "platejs/react";

import { getBridge } from "@/renderer/lib/bridge";

export const AI_MARK = "ai";

// A leaf-only plugin: the `ai` mark just needs to exist so the editor renders it
// (highlight styling is registered in markdown-editor's components).
export const AiMarkKit = [createPlatePlugin({ key: AI_MARK, node: { isLeaf: true } })];

export type InlineAiAction = "continue" | "summarize" | "improve" | "shorter" | "grammar";

const AI_EDIT_ACTIONS = new Set<InlineAiAction>(["improve", "shorter", "grammar"]);

export type InlineAiStatus =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "pending"; action: InlineAiAction }
  | { kind: "error"; message: string };

const PROMPT_BASE =
  "You are a writing assistant inside a notes editor. Respond with ONLY the resulting text — no preamble, no surrounding quotes, no markdown code fences, no explanation.";

function buildPrompt(action: InlineAiAction, text: string): string {
  switch (action) {
    case "continue":
      return `${PROMPT_BASE}\n\nContinue the following text naturally with one short paragraph:\n\n${text}`;
    case "summarize":
      return `${PROMPT_BASE}\n\nWrite a concise summary of the following:\n\n${text}`;
    case "improve":
      return `${PROMPT_BASE}\n\nRewrite the following to be clearer and better written, keeping the meaning:\n\n${text}`;
    case "shorter":
      return `${PROMPT_BASE}\n\nRewrite the following to be more concise, keeping the meaning:\n\n${text}`;
    case "grammar":
      return `${PROMPT_BASE}\n\nFix spelling and grammar in the following, keeping the meaning and tone:\n\n${text}`;
  }
}

// Insert `text` as an AI-marked range: replacing the selection for edit actions,
// or at the cursor for generate actions. Returns the inserted range.
function insertAi(editor: PlateEditor, text: string, mode: "replace" | "insert"): TRange | null {
  if (mode === "insert") editor.tf.collapse({ edge: "end" });
  const sel = editor.selection;
  if (!sel) return null;
  const anchor = RangeApi.start(sel);
  editor.tf.insertText(text);
  const focus = editor.selection?.anchor;
  if (!focus) return null;
  const range: TRange = { anchor, focus };
  editor.tf.setNodes({ [AI_MARK]: true }, { at: range, match: (n) => "text" in n, split: true });
  // Select the pending text so it reads as a distinct, highlighted proposal and
  // the Accept/Discard bar can anchor to it.
  editor.tf.select(range);
  return range;
}

export function useInlineAi(editor: PlateEditor): {
  status: InlineAiStatus;
  run: (action: InlineAiAction) => void;
  accept: () => void;
  discard: () => void;
  dismissError: () => void;
} {
  const [status, setStatus] = useState<InlineAiStatus>({ kind: "idle" });
  const pendingRef = useRef<ReturnType<PlateEditor["api"]["rangeRef"]> | null>(null);

  const run = useCallback(
    (action: InlineAiAction) => {
      const bridge = getBridge();
      const sel = editor.selection;
      if (!bridge || !sel) return;
      const hasSelection = !RangeApi.isCollapsed(sel);
      const isEdit = AI_EDIT_ACTIONS.has(action);
      if (isEdit && !hasSelection) return;

      const input =
        isEdit || (action === "summarize" && hasSelection)
          ? editor.api.string(sel)
          : editor.api.string([]);

      setStatus({ kind: "loading" });
      void bridge
        .generateInlineAi({ prompt: buildPrompt(action, input) })
        .then((result) => {
          if (!result.ok) {
            setStatus({ kind: "error", message: result.error });
            return undefined;
          }
          const range = insertAi(editor, result.text, isEdit ? "replace" : "insert");
          pendingRef.current = range ? editor.api.rangeRef(range) : null;
          setStatus({ kind: "pending", action });
          return undefined;
        })
        .catch(() => setStatus({ kind: "error", message: "AI request failed." }));
    },
    [editor],
  );

  const finish = useCallback(
    (mode: "accept" | "discard") => {
      const ref = pendingRef.current;
      const range = ref?.current;
      if (range) {
        if (mode === "accept") {
          editor.tf.unsetNodes([AI_MARK], { at: range, match: (n) => "text" in n, split: true });
        } else {
          editor.tf.delete({ at: range });
        }
      }
      ref?.unref();
      pendingRef.current = null;
      setStatus({ kind: "idle" });
      editor.tf.focus();
    },
    [editor],
  );

  return {
    status,
    run,
    accept: () => finish("accept"),
    discard: () => finish("discard"),
    dismissError: () => setStatus({ kind: "idle" }),
  };
}
