version: '3'

services:
  potion_pg:
    container_name: potion_pg
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env.local
    volumes:
      - potion_pg_data:/data/postgres

  potion_redis:
    container_name: potion_redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - potion_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  potion_pg_data:
  potion_redis_data:
