import { useCallback, useEffect, useState, type FormEventHandler } from "react";
import useMutation from "swr/mutation";
import useFetchAuthFactors from "~/core/hooks/use-fetch-factors";
import useSignOut from "~/core/hooks/use-sign-out";
import useSupabase from "~/core/hooks/use-supabase";
import { Alert } from "~/components/Alert";
import { Button } from "~/components/Button";
import { If } from "~/components/If";
import Spinner from "~/components/Spinner";
import { Text } from "~/components/Text";
import VerificationCodeInput from "./VerificationCodeInput";

const MultiFactorChallengeContainer = ({
  onSuccess,
}: React.PropsWithChildren<{
  onSuccess: () => void;
}>) => {
  const [factorId, setFactorId] = useState("");
  const [verifyCode, setVerifyCode] = useState("");
  const mutation = useVerifyMFAChallenge();

  const onSubmitClicked: FormEventHandler<HTMLFormElement> = useCallback(
    async (event) => {
      event.preventDefault();

      if (!factorId || !verifyCode) {
        return;
      }

      await mutation.trigger({
        factorId,
        verifyCode,
      });

      onSuccess();
    },
    [factorId, mutation, onSuccess, verifyCode],
  );

  if (!factorId) {
    return (
      <FactorsListContainer onSelect={setFactorId} onSuccess={onSuccess} />
    );
  }

  return (
    <form onSubmit={onSubmitClicked}>
      <div className="flex flex-col space-y-4">
        <span className="text-sm">
          Enter the verification code generated by your authenticator app
        </span>

        <div className="flex w-full flex-col space-y-2.5">
          <VerificationCodeInput
            onInvalid={() => setVerifyCode("")}
            onValid={setVerifyCode}
          />

          <If condition={mutation.error}>
            <Alert type="error">
              Invalid verification code. Please try again
            </Alert>
          </If>
        </div>

        <Button loading={mutation.isMutating} disabled={!verifyCode}>
          {mutation.isMutating
            ? "Verifying code..."
            : "Submit Verification Code"}
        </Button>
      </div>
    </form>
  );
};

export default MultiFactorChallengeContainer;

const useVerifyMFAChallenge = () => {
  const client = useSupabase();

  return useMutation(
    ["mfa-verify-challenge"],
    async (
      _,
      {
        arg,
      }: {
        arg: {
          factorId: string;
          verifyCode: string;
        };
      },
    ) => {
      const { factorId, verifyCode: code } = arg;

      const response = await client.auth.mfa.challengeAndVerify({
        factorId,
        code,
      });

      if (response.error) {
        throw response.error;
      }

      return response.data;
    },
  );
};

const FactorsListContainer = ({
  onSuccess,
  onSelect,
}: React.PropsWithChildren<{
  onSuccess: () => void;
  onSelect: (factor: string) => void;
}>) => {
  const signOut = useSignOut();

  const { data: factors, isLoading, error } = useFetchAuthFactors();

  const isSuccess = factors && !isLoading && !error;

  useEffect(() => {
    // If there are no factors, continue
    if (isSuccess && !factors.totp.length) {
      onSuccess();
    }
  }, [factors?.totp.length, isSuccess, onSuccess]);

  useEffect(() => {
    // If there is an error, sign out
    if (error) {
      void signOut();
    }
  }, [error, signOut]);

  useEffect(() => {
    // If there is only one factor, select it automatically
    if (isSuccess && factors.totp.length === 1) {
      onSelect(factors.totp[0].id);
    }
  });

  if (isLoading) {
    return (
      <div className="flex flex-col items-center space-y-4 py-8">
        <Spinner />

        <div>Loading factors...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="w-full">
        <Alert type="error">Error loading factors list</Alert>
      </div>
    );
  }

  const verifiedFactors = factors?.totp ?? [];

  return (
    <div className="flex flex-col space-y-4">
      <div>
        <Text>Choose a factor to verify your identity</Text>
      </div>

      {verifiedFactors.map((factor) => (
        <div key={factor.id}>
          <Button onClick={() => onSelect(factor.id)}>
            {factor.friendly_name}
          </Button>
        </div>
      ))}
    </div>
  );
};
