// Inline AI for the editor — continue / summarize / improve / shorten / fix,
// generated by the isolated no-tools agent (main/inline-ai.ts) and inserted as a
// highlighted "pending" range the user can Accept (keep) or Discard (remove).
//
// The pending text carries a transient `ai` leaf mark (for the highlight) and is
// tracked by a rangeRef so accept/discard target it exactly even if the doc
// shifts. The mark has no markdown form, so it's simply dropped on serialize —
// accepting just removes the highlight; the text was already in the document.

import { useCallback, useRef, useState } from "react";
import { type TRange, PointApi, RangeApi } from "platejs";
import { PlateLeaf, createPlatePlugin, type PlateEditor, type PlateLeafProps } from "platejs/react";

import { getBridge } from "@repo/app/lib/bridge";

export const AI_MARK = "ai";

function AiLeaf(props: PlateLeafProps) {
  return (
    <PlateLeaf
      {...props}
      className="rounded-sm bg-primary/15 underline decoration-primary/40 decoration-dotted underline-offset-2"
    />
  );
}

// A leaf-only plugin: the `ai` mark exists so the editor renders the pending
// highlight; it never serializes (markdown-kit's disallowedNodes).
export const AiMarkKit = [
  createPlatePlugin({ key: AI_MARK, node: { isLeaf: true } }).withComponent(AiLeaf),
];

export type InlineAiAction = "continue" | "summarize" | "improve" | "shorter" | "grammar";

const AI_EDIT_ACTIONS = new Set<InlineAiAction>(["improve", "shorter", "grammar"]);

export type InlineAiStatus =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "pending"; action: InlineAiAction }
  | { kind: "error"; message: string };

const PROMPT_BASE =
  "You are a writing assistant inside a notes editor. Respond with ONLY the resulting text — no preamble, no surrounding quotes, no markdown code fences, no explanation.";

function buildPrompt(action: InlineAiAction, text: string): string {
  switch (action) {
    case "continue":
      return `${PROMPT_BASE}\n\nContinue the following text naturally with one short paragraph:\n\n${text}`;
    case "summarize":
      return `${PROMPT_BASE}\n\nWrite a concise summary of the following:\n\n${text}`;
    case "improve":
      return `${PROMPT_BASE}\n\nRewrite the following to be clearer and better written, keeping the meaning:\n\n${text}`;
    case "shorter":
      return `${PROMPT_BASE}\n\nRewrite the following to be more concise, keeping the meaning:\n\n${text}`;
    case "grammar":
      return `${PROMPT_BASE}\n\nFix spelling and grammar in the following, keeping the meaning and tone:\n\n${text}`;
  }
}

// Serial ids so a stale stream event from a previous request is ignored.
let requestCounter = 0;

export function useInlineAi(editor: PlateEditor): {
  status: InlineAiStatus;
  run: (action: InlineAiAction) => void;
  accept: () => void;
  discard: () => void;
  dismissError: () => void;
} {
  const [status, setStatus] = useState<InlineAiStatus>({ kind: "idle" });
  // The editor history length before the AI touched the doc; Discard undoes back
  // to it, reverting the delete + every streamed insert in one clean step.
  const undoDepthRef = useRef(0);

  const run = useCallback(
    (action: InlineAiAction) => {
      const bridge = getBridge();
      const sel = editor.selection;
      if (!bridge || !sel) return;
      const hasSelection = !RangeApi.isCollapsed(sel);
      const isEdit = AI_EDIT_ACTIONS.has(action);
      if (isEdit && !hasSelection) return;

      const input =
        isEdit || (action === "summarize" && hasSelection)
          ? editor.api.string(sel)
          : editor.api.string([]);

      // Remember where the history stood so Discard can revert everything below.
      undoDepthRef.current = editor.history.undos.length;
      // Clear the target (edit actions replace the selection) or drop to its end
      // (generate actions), then track the start so the streamed deltas form one
      // accept/discard-able range.
      if (isEdit) editor.tf.delete();
      else editor.tf.collapse({ edge: "end" });
      const insertion = editor.selection;
      if (!insertion) return;
      const startRef = editor.api.pointRef(RangeApi.start(insertion));

      requestCounter += 1;
      const requestId = String(requestCounter);
      setStatus({ kind: "loading" });

      // Insert each streamed delta, AI-marked, at the growing end of the range.
      const off = bridge.onAiStreamed(({ requestId: id, delta }) => {
        if (id !== requestId || delta.length === 0) return;
        editor.tf.addMark(AI_MARK, true);
        editor.tf.insertText(delta);
      });

      void bridge
        .generateInlineAi({ prompt: buildPrompt(action, input), requestId })
        .then((result) => {
          off();
          const start = startRef.current;
          startRef.unref();
          const end = editor.selection?.anchor;
          if (!result.ok) {
            if (start && end) editor.tf.delete({ at: { anchor: start, focus: end } });
            setStatus({ kind: "error", message: result.error });
            return undefined;
          }
          // Fallback for models that don't stream: insert the final text now.
          if (start && end && PointApi.equals(start, end)) {
            editor.tf.addMark(AI_MARK, true);
            editor.tf.insertText(result.text);
          }
          const focus = editor.selection?.anchor;
          if (start && focus) {
            const range: TRange = { anchor: start, focus };
            editor.tf.setNodes(
              { [AI_MARK]: true },
              {
                at: range,
                match: (n) => "text" in n,
                split: true,
              },
            );
            editor.tf.select(range);
          }
          setStatus({ kind: "pending", action });
          return undefined;
        })
        .catch(() => {
          off();
          startRef.unref();
          setStatus({ kind: "error", message: "AI request failed." });
        });
    },
    [editor],
  );

  const finish = useCallback(
    (mode: "accept" | "discard") => {
      if (mode === "accept") {
        // Keep the text, just strip the highlight everywhere it landed.
        editor.tf.unsetNodes([AI_MARK], { at: [], match: (n) => AI_MARK in n, mode: "lowest" });
        editor.tf.collapse({ edge: "end" });
      } else {
        // Revert the delete + every streamed insert back to the pre-AI state.
        while (editor.history.undos.length > undoDepthRef.current) editor.undo();
      }
      setStatus({ kind: "idle" });
      editor.tf.focus();
    },
    [editor],
  );

  return {
    status,
    run,
    accept: () => finish("accept"),
    discard: () => finish("discard"),
    dismissError: () => setStatus({ kind: "idle" }),
  };
}
