import { afterAll, beforeAll, expect, test } from "vitest";

import { user } from "../drizzle-schema-auth";
import { waitlist } from "../drizzle-schema";
import { createTestDb, type TestDb } from "../testing/pglite";

/**
 * SPIKE proving the linchpin of the verification rearchitecture: the real
 * Drizzle schema can be stood up and queried entirely in-process, with no
 * Docker / Supabase / network, so DB-backed code is verifiable in the cloud
 * container.
 */
let db: TestDb;
let close: () => Promise<void>;

beforeAll(async () => {
  ({ db, close } = await createTestDb());
});

afterAll(async () => {
  await close?.();
});

test("real schema applies to PGlite and round-trips a row", async () => {
  await db.insert(user).values({ id: "u_1", name: "Ada", email: "ada@example.com" });

  await db.insert(waitlist).values({ email: "ada@example.com", userId: "u_1", source: "spike" });

  const rows = await db.select().from(waitlist);

  expect(rows).toHaveLength(1);
  expect(rows[0]?.email).toBe("ada@example.com");
  expect(rows[0]?.id).toBeTruthy(); // defaultRandom() uuid generated by the engine
});

test("foreign-key constraint from the real schema is enforced", async () => {
  await expect(
    db.insert(waitlist).values({ email: "nobody@example.com", userId: "does-not-exist" }),
  ).rejects.toThrow();
});
